"""Migração inicial

Revision ID: 0a99707282d7
Revises: 
Create Date: 2025-02-03 20:03:53.604069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a99707282d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a001_usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a001_login', sa.String(length=50), nullable=False),
    sa.Column('a001_senha', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('a001_login')
    )
    op.create_table('a002_licenca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a002_cnpj', sa.String(length=30), nullable=False),
    sa.Column('a002_cliente', sa.String(length=50), nullable=True),
    sa.Column('a002_ativo', sa.String(length=3), nullable=True),
    sa.Column('a002_renomear', sa.String(length=3), nullable=True),
    sa.Column('a002_aviso', sa.String(length=100), nullable=True),
    sa.Column('a002_data_hora', sa.String(length=30), nullable=True),
    sa.Column('a002_sql', sa.Text(), nullable=True),
    sa.Column('a002_validade_licenca', sa.DateTime(), nullable=True),
    sa.Column('a002_product_key', sa.String(length=50), nullable=True),
    sa.Column('a002_product_key_token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('a002_cnpj')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('a002_licenca')
    op.drop_table('a001_usuarios')
    # ### end Alembic commands ###
