"""Adiciona coluna a001_funcao

Revision ID: 189f6075fc3f
Revises: 73c7095003dd
Create Date: 2025-02-17 10:00:02.157520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189f6075fc3f'
down_revision: Union[str, None] = '73c7095003dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('a001_usuarios', sa.Column('a001_funcao', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('a001_usuarios', 'a001_funcao')
    # ### end Alembic commands ###
