"""Adiciona código

Revision ID: 73c7095003dd
Revises: 0a99707282d7
Create Date: 2025-02-14 18:38:55.538847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c7095003dd'
down_revision: Union[str, None] = '0a99707282d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('a001_usuarios', sa.Column('a001_codigo', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('a001_usuarios', 'a001_codigo')
    # ### end Alembic commands ###
